name: imperium
description: "Imperium - Personal Finance App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7

  # Dependency Injection
  get_it: ^8.0.3
  injectable: ^2.5.0

  # Navigation
  go_router: ^14.6.2

  # Database
  drift: ^2.22.1
  sqlite3_flutter_libs: ^0.5.28
  path_provider: ^2.1.5
  path: ^1.9.1

  # Network
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  web_socket_channel: ^3.0.1

  # Utils
  intl: ^0.19.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.16
  uuid: ^4.5.1
  dartz: ^0.10.1
  shared_preferences: ^2.3.4

  # Image
  image_picker: ^1.0.7

  # Video
  video_player: ^2.9.2

  # UI
  cupertino_icons: ^1.0.8

  # Charts
  fl_chart: ^0.69.0

  # Color Picker
  flex_color_picker: ^3.6.0

  # Google Calendar Integration
  google_sign_in: ^6.2.1
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.12
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  injectable_generator: ^2.6.3
  drift_dev: ^2.22.1
  bloc_test: ^9.1.7
  mocktail: ^1.0.4

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/videos/
    - assets/images/
